# https://github.com/rust-lang/rust/blob/master/.github/workflows/ci.yml
# https://github.com/launchbadge/sqlx/blob/master/.github/workflows/sqlx.yml
# https://github.com/dh1tw/remoteAudio/blob/master/.github/workflows/build.yml
# https://github.com/ClementTsang/bottom/blob/master/.github/workflows/ci.yml
# https://github.com/actions-rs
# TODO: Set CRATE_NAME to match the project name
name: CI
env:
  CRATE_NAME: pastebin
  BINARY_NAME: pastebin

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.triple.os }}
    continue-on-error: true

    strategy:
      fail-fast: false
      matrix:
        triple:
          - {
              os: "ubuntu-18.04",
              target: "x86_64-unknown-linux-gnu",
              cross: false,
            }

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ matrix.triple.target }}-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.triple.target }}-build-

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          target: ${{ matrix.triple.target }}
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release ${{ matrix.triple.ssl }} --target=${{ matrix.triple.target }}
          use-cross: ${{ matrix.triple.cross }}

      - name: Optionally strip and upx
        if: ${{ !matrix.triple.cross }}
        uses: svenstaro/upx-action@2.0.1
        with:
          file: target/${{ matrix.triple.target }}/release/${{ env.BINARY_NAME }}${{ matrix.triple.suffix }}
          args: --best
          strip: true

      - uses: actions/upload-artifact@master
        with:
          name: ${{ env.CRATE_NAME }}-${{ matrix.triple.target }}${{ matrix.triple.suffix }}
          path: target/${{ matrix.triple.target }}/release/${{ env.BINARY_NAME }}${{ matrix.triple.suffix }}

      - name: Get VERSION
        if: startsWith(github.ref, 'refs/tags/v')
        id: get_version
        shell: bash
        run: |
          echo "::set-output name=VERSION::${GITHUB_REF#refs/tags/}"

      - name: Renaming file before uploading
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
        shell: bash
        run: |
          cp target/${{ matrix.triple.target }}/release/${{ env.BINARY_NAME }}${{ matrix.triple.suffix }} ${{ env.BINARY_NAME }}-$VERSION-${{ matrix.triple.target }}${{ matrix.triple.suffix }}

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          draft: true
          prerelease: false
          files: ${{ env.BINARY_NAME }}-${{ steps.get_version.outputs.VERSION }}-${{ matrix.triple.target }}${{ matrix.triple.suffix }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
